### ISSUE TITLE
RTS/DTR toggling during -s serial session

### ISSUE THREAD

**Issue by JohnOH** [jeelabs/embello#11]
Add support for toggling the RTS and the DTR signals passed to the FDTI card either directly of via TCP. Perhaps <ctl>r and <ctl>d could be used. This would offer the ability to halt the running code by placing the LPC into reset.

**Comment by JohnOH** [comment]
The ability to connect to the LPC without triggering a reset would also be very useful.

**Comment by jcw** [comment]
Could be done similar to [PicoCom](http://linux.die.net/man/8/picocom) - ctrl-p pulses DTR and ctrl-t toggles it. Perhaps with ctrl-r to pulse RTS for a reset (no need for a toggle, I think).

**Comment by JohnOH** [comment]
Toggle for RTS would I guess allow us to told the processor in reset - not executing code.

Best Regards, John.

**Comment by jcw** [comment]
Ok, that suggests ctrl-o (off). Could indeed be of use.
