### ISSUE TITLE
Add `compiletoram` at end of all include files

### ISSUE THREAD

**Issue by tht** [jeelabs/embello#30]
Just an idea…

I've started to use `g6s/board.fs` independent of the other files and was kinda surprised because after loading `board.fs` all my new word definitions have been put into flash.

What do you think about adding `compiletoram` at the end of all these include files? Just to make sure we always switch back to the *default* behavior (compiletoram).

**Comment by jcw** [comment]
Yes, good idea. I removed it a while back, but this will avoid such surprises.
Leaving this open for now, to remind me to make the changes - probably in about a week.
