### ISSUE TITLE
README doesn't mention i2c port

### ISSUE THREAD

**Issue by JohnOH** [jeelabs/embello#34]
A photograph of the completed board would be helpful. My take is that the expander is underneath the HyTiny, on the opposite side to the processor. The radio and silk screen is also on the bottom, not between the boards. 

The existing six pin GND/SWCLK/SWDIO.RX/TX/3v3 connector to be removed and re-provided through to the expander board's matching six pins.

**Comment by jcw** [comment]
Photos added. You can use long pin headers if you want to keep access to the HyTiny's 6-pin header.
