### ISSUE TITLE
2.1MHz and 16MHz are leaving a value on stack

### ISSUE THREAD

**Issue by SevenW** [jeelabs/embello#50]

**Comment by SevenW** [comment]
... but may not be using most recent embello....

**Comment by SevenW** [comment]
` : us/cycl-factor 65536 1000000 um* clock-hz @ um/mod us/cycle*2^16 ! ;` 
 in stm32l0 hal.fs needs a drop at the end to remove the remainder of the um/mod

**Comment by jcw** [comment]
Ah, good catch - fixed in latest commit.
