### ISSUE TITLE
stm32f4/io.fs incorrectly using stm32f1 register layout

### ISSUE THREAD

**Issue by pelrun** [jeelabs/embello#60]
The F4 has the io mode and PP/OD state in separate registers, unlike the F1 where they're interleaved in CRL/CRH. The constants and the io-mode! word are copied almost verbatim from the F1 code and are therefore not working.

**Comment by jcw** [comment]
Maybe the [stm32l0/io.fs](https://github.com/jeelabs/embello/blob/master/explore/1608-forth/flib/stm32l0/io.fs) code would be a better starting point? I haven't used the F4 much, I admit.

**Comment by pelrun** [comment]
I managed to put together a working replacement myself, but since it's pretty much the first real Forth I've written it's pretty suboptimal :) - I'll test the L0 code and if it's good (or only needs minor tweaks) I'll report back.
