### ISSUE TITLE
i2c on stm32f1 reading 1-byte replies

### ISSUE THREAD

**Issue by smurfix** [jeelabs/embello#62]
Hi,
I seem to be unable to read a 1-byte reply on i2c.
Looking at i2c-xfer, that case seems to be a no-op

> 1 of endof                ( cnt = 1 )

This can't possibly be correct … unless I'm missing something fundamental.

**Comment by jcw** [comment]
Hm, odd indeed - that's a new driver, we'll have to ask @pragtich for help on this one.

You can switch to the bit-banged version, i.e. use the `flib/any/i2c-bb.fs` driver instead until this issue gets resolved.

**Comment by pragtich** [comment]
Oops,
You're right, of course. I had postponed implementing that option till I understood the rest. 
I might have some time to fix it over the weekend, shouldn't be too complicated.
I clearly need a test suite :-)
