### ISSUE TITLE
BME280 typo

### ISSUE THREAD

**Issue by doewie** [jeelabs/embello#70]
The bme280 driver , bme-reset leaves some bytes on the stack.
I think [this line](https://github.com/jeelabs/embello/blob/master/explore/1608-forth/flib/i2c/bme280.fs#L8) should read :
`$E0 >i2c $B6 >i2c`
i.s.o.
`$E0 >i2c $B6`

**Comment by tve** [comment]
You are correct, I can't explain how that snuck in. $E0-$B6 is the correct reset sequence.
