### ISSUE TITLE
rf-listen started second time does not report packets (spi-init related?)

### ISSUE THREAD

**Issue by g2pmas** [jeelabs/embello#71]
I noticed that after stopping "rf-listen" by keypressd and restart, it does not report packet anymore. The same happens when before start for first time "rf-listen" i call "spi-init" (that is already in "rf-init").
It happens on both TinyExtender hardware and jz4.

**Comment by tve** [comment]
This is because rf.mode does not get reset and as a consequence rf-recv thinks the radio is already in RX mode the second time around when in fact it has just be initialized and sits in sleep mode. This is fixed in my PR #67 (line 91).
