### ISSUE TITLE
BMP280 driver. bme-reset leaves nak on the stack

### ISSUE THREAD

**Issue by doewie** [jeelabs/embello#72]
Still a problem with the BMP280 driver in [this line](https://github.com/jeelabs/embello/blob/master/explore/1608-forth/flib/i2c/bme280.fs)
bme-reset leaves the NAK  from i2c-xfer on the stack

So either the definition should be:
`:bme-reset ( -- nak )`

or the last line should be ( probably better ?) :
`0 i2c-xfer  drop ;`

**Comment by tve** [comment]
mhh, I need to look why I've not been hitting these issues. Thanks for flagging!

**Comment by tve** [comment]
I guess my temperature node has simply always carried two extra words on the stack and I never noticed... As you point out, there is a drop missing...

**Comment by tve** [comment]
Thanks for flagging the issues!
