### ISSUE TITLE
USART1-BRR wrong offset in stm32l0/hal.fs

### ISSUE THREAD

**Issue by hirnidrin** [jeelabs/embello#81]
Code:
```
$40013800 constant USART1
USART1 $8 + constant USART1-BRR
```
According to the [STM32L0x3 reference manual](www.st.com/resource/en/reference_manual/dm00095744.pdf) page 803, the BRR register has an offset of $C (not $8).

**Comment by jcw** [comment]
Aha, many thanks! - This is not being used now, since Mecrisp controls USART1, but it's still a bug.
